blank_issues_enabled: true
contact_links:
  - name: OpenHornet Discord Server
    url: https://discord.gg/G5PA5ju
    about: Not sure if your issue is an actual bug or not? Join us in Discord and let's chat about it!
  - name: Lost and don't know where to start?
    url: https://openhornet.com/start-here/
    about: Click here to go to the OpenHornet website and view the getting started page!